
CREATE TABLE dep_fed_results (
	id INTEGER NOT NULL, 
	dt_geracao VARCHAR(1024), 
	hh_geracao VARCHAR(1024), 
	ano_eleicao VARCHAR(1024), 
	cd_tipo_eleicao INTEGER, 
	nm_tipo_eleicao VARCHAR(1024), 
	nr_turno INTEGER, 
	cd_eleicao INTEGER, 
	ds_eleicao VARCHAR(1024), 
	dt_eleicao VARCHAR(1024), 
	tp_abrangencia VARCHAR(1024), 
	sg_uf VARCHAR(1024), 
	sg_ue VARCHAR(1024), 
	nm_ue VARCHAR(1024), 
	cd_municipio INTEGER, 
	cd_mun VARCHAR(1024), 
	nm_municipio VARCHAR(1024), 
	nr_zona INTEGER, 
	cd_cargo INTEGER, 
	ds_cargo VARCHAR(1024), 
	sq_candidato VARCHAR(1024), 
	nr_candidato INTEGER, 
	nm_candidato VARCHAR(1024), 
	nm_urna_candidato VARCHAR(1024), 
	nm_social_candidato VARCHAR(1024), 
	cd_situacao_candidatura INTEGER, 
	ds_situacao_candidatura VARCHAR(1024), 
	cd_detalhe_situacao_cand INTEGER, 
	ds_detalhe_situacao_cand VARCHAR(1024), 
	cd_situacao_julgamento INTEGER, 
	ds_situacao_julgamento VARCHAR(1024), 
	cd_situacao_cassacao INTEGER, 
	ds_situacao_cassacao VARCHAR(1024), 
	cd_situacao_diploma INTEGER, 
	ds_situacao_diploma VARCHAR(1024), 
	tp_agremiacao VARCHAR(1024), 
	nr_partido INTEGER, 
	sg_partido VARCHAR(1024), 
	nm_partido VARCHAR(1024), 
	nr_federacao INTEGER, 
	nm_federacao VARCHAR(1024), 
	sg_federacao VARCHAR(1024), 
	ds_composicao_federacao VARCHAR(1024), 
	sq_coligacao VARCHAR(1024), 
	nm_coligacao VARCHAR(1024), 
	ds_composicao_coligacao VARCHAR(1024), 
	st_voto_em_transito VARCHAR(1024), 
	qt_votos_nominais INTEGER, 
	nm_tipo_destinacao_votos VARCHAR(1024), 
	qt_votos_nominais_validos INTEGER, 
	cd_sit_tot_turno INTEGER, 
	ds_sit_tot_turno VARCHAR(1024), 
	PRIMARY KEY (id)
)


CREATE TABLE distribuicao_populacao (
	id INTEGER NOT NULL, 
	cd_municipio INTEGER, 
	cd_mun VARCHAR(1024), 
	nm_mun VARCHAR(1024), 
	tot_pop INTEGER, 
	abs_pop_branca INTEGER, 
	abs_pop_preta INTEGER, 
	abs_pop_amarela INTEGER, 
	abs_pop_parda INTEGER, 
	abs_pop_indigena INTEGER, 
	ignorados INTEGER, 
	perc_branca FLOAT, 
	perc_preta FLOAT, 
	perc_amarela FLOAT, 
	perc_parda FLOAT, 
	perc_indigena FLOAT, 
	abs_indigena_cor_raca INTEGER, 
	perc_indigena_cor_raca FLOAT, 
	PRIMARY KEY (id)
)


CREATE TABLE pib_municipios (
	id INTEGER NOT NULL, 
	ano INTEGER, 
	cd_grande_regiao VARCHAR(1024), 
	nm_grande_regiao VARCHAR(1024), 
	cd_uf INTEGER, 
	sg_uf VARCHAR(1024), 
	nm_uf VARCHAR(1024), 
	cd_municipio INTEGER, 
	cd_mun VARCHAR(1024), 
	nm_mun VARCHAR(1024), 
	reg_metrop VARCHAR(1024), 
	cd_mesorg INTEGER, 
	nm_mesorg VARCHAR(1024), 
	cd_microrg INTEGER, 
	nm_microrg VARCHAR(1024), 
	cd_rgi INTEGER, 
	nm_rgi VARCHAR(1024), 
	mun_rgi VARCHAR(1024), 
	cd_rgitmd INTEGER, 
	nm_rgitmd VARCHAR(1024), 
	mun_rgitmd VARCHAR(1024), 
	cd_conc_urb INTEGER, 
	nm_conc_urb VARCHAR(1024), 
	tp_conc_urb VARCHAR(1024), 
	cd_arj_pop INTEGER, 
	nm_arj_pop VARCHAR(1024), 
	hierarquia_urb VARCHAR(1024), 
	hierarquia_urb_categ VARCHAR(1024), 
	cd_reg_rural INTEGER, 
	nm_reg_rural VARCHAR(1024), 
	reg_rural_clas_nuc VARCHAR(1024), 
	amazonia_legal VARCHAR(1024), 
	semiarido VARCHAR(1024), 
	reg_sp VARCHAR(1024), 
	vb_pecuaria INTEGER, 
	vb_indust INTEGER, 
	vb_servicos INTEGER, 
	vb_adm INTEGER, 
	vb_total INTEGER, 
	impostos INTEGER, 
	pib INTEGER, 
	pip_per_capita FLOAT, 
	atv_maior_vb VARCHAR(1024), 
	atv_seg_maior_vb VARCHAR(1024), 
	atv_terc_maior_vb VARCHAR(1024), 
	PRIMARY KEY (id)
)

CREATE TABLE transferencias_aggregadas_sc (
    nmmunicipiocredor VARCHAR(100), 
    nmfuncao VARCHAR(100),         
    vlempenhado DECIMAL(15, 2),    
    vlliquidado DECIMAL(15, 2),    
    vlpagoorcamentario DECIMAL(15, 2), 
    valor_total DECIMAL(15, 2)     
);

CREATE TABLE correlacao_votacao_transferencias (
    id SERIAL PRIMARY KEY,                       
    cd_mun VARCHAR(10),                         
    nm_municipio VARCHAR(100),                  
    qt_votos_nominais INT,                      
    qt_votos_validos INT,                       
    nmfuncao VARCHAR(100),                      
    vlempenhado DECIMAL(15, 2),                 
    vlliquidado DECIMAL(15, 2),                 
    vlpagoorcamentario DECIMAL(15, 2),          
    valor_total DECIMAL(15, 2),                 
    geom GEOMETRY,                              
    area_km2 DECIMAL(15, 2),                    
    cd_rgi VARCHAR(10),                         
    nm_rgi VARCHAR(100),                        
    cd_rgint VARCHAR(10),                       
    nm_rgint VARCHAR(100)                       
);


